#!/bin/bash

cd /srv/samba/share
#echo "starting">>/srv/samba/share/DexRun.log
pkill -e -x DexRun
#echo "Stil alive">>/srv/samba/share/DexRun.log
# -x stops this # don't use the !/bin/bash thing because then pkill will kill Run"DexRun"
#if  [ $(date -d "01/01/1970" +%s) -lt $(date +%s) ]; then
	if  [ $(date -r /srv/samba/share/DexRun +%s) -lt $(date -r /srv/samba/share/DexRun.c +%s) ]; then
		echo "">>/srv/samba/share/DexRun.log
		echo "Compiling DexRun.c $(date -r /srv/samba/share/DexRun.c +%Y%m%d_%H:%M:%S)">>/srv/samba/share/DexRun.log
		echo " replacing DexRun $(date -r /srv/samba/share/DexRun +%Y%m%d%_%H:%M:%S)">>/srv/samba/share/DexRun.log
		cd /usr/src/xillinux/xillybus-lite/demo
		cp -f -p /srv/samba/share/DexRun.c . 
		#-p option copies file date stamp set time before editing DexRun.c
		make
		cp -f DexRun /srv/samba/share/.
		touch -t $(date -r DexRun.c +%Y%m%d%H%M.%S) /srv/samba/share/DexRun
		#set the timestamp of the compiled file to that of the source file
		#so we don't keep re-compiling if the date isn't set
		ls -l DexRun >>/srv/samba/share/DexRun.log
		fi
#	fi

cd /srv/samba/share
#echo "running">>/srv/samba/share/DexRun.log
./DexRun 1 3 1 &

# sleep 5 && sudo nano core define_and_start_job /srv/samba/share/autoexec.dde
